# -*- coding: utf-8 -*-
"""Expenses project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IZAB4bUVT-hxUSMyNlywnymPfd8-nzgC
"""

import pandas as pd
import matplotlib.pyplot as plt



def create_budget():
    budget= pd.DataFrame(columns=['Category','Budgeted_Amount'])
    categories= input("Enter budget category: ").split(',')

    for category in categories:
        budget_amount= float(input(f"Enter the budget amount for {category.strip()}: "))
        budget=budget.append({'Category': category.strip(), 'Budgeted_Amount': budget_amount},ignore_index=True)

    return budget




def record_actual_expenses(budget):
    actual_expenses= pd.DataFrame(columns=['Category','Actual_Expenses'])

    for _,row in budget.iterrows():
        category= row["Category"]
        actual_amount= float(input(f'Enter the actual spent for {category}: '))
        actual_expenses= actual_expenses.append({'Category': category, 'Actual_Expenses': actual_amount}, ignore_index= True)

    return actual_expenses


def analyse_budget_vs_actuals(budget, actual_expenses):
    analysis= pd.merge(budget,actual_expenses, on= "Category" )
    analysis['Variance']= analysis["Actual_Expenses"]- analysis["Budgeted_Amount"]
    return analysis



def main():
    budget= create_budget()
    actual_expenses= record_actual_expenses(budget)
    analysis= analyse_budget_vs_actuals(budget, actual_expenses)

    print("\nbudget vs Actual budget: ")
    print(analysis)

    total_variance= analysis['Variance'].sum()
    print(f"total_variance: ${total_variance:.2f}")



if __name__==  "__main__" :
    main()